close all;
figure(1);
subplot(311);
plot(t,x(:,1),'b','linewidth',2);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
xlabel('Time(s)');ylabel('x');
legend('x');
subplot(312);
plot(t,x(:,3),'b','linewidth',2);
xlabel('Time(s)');ylabel('y');
legend('y');
subplot(313);
zd=3*t./t;
plot(t,x(:,5),'b','linewidth',2);
xlabel('Time(s)');ylabel('z');
legend('z');

figure(2);
subplot(311);
plot(t,x(:,7)/pi*180,'k','linewidth',2);
legend('\phi (degree)');
subplot(312);
plot(t,x(:,9)/pi*180,'k','linewidth',2);
legend('\theta (degree)');
subplot(313);
plot(t,x(:,11)/pi*180,'k','linewidth',2);
legend('\psi (degree)');
figure(3);
subplot(411);
plot(t,ut(:,1),'k','linewidth',2);
legend('u1');
subplot(412);
plot(t,ut(:,2),'k','linewidth',2);
legend('u2');
subplot(413);
plot(t,ut(:,3),'k','linewidth',2);
legend('u3');
subplot(414);
plot(t,ut(:,4),'k','linewidth',2);
legend('u4');